version: '3.1'
services:
  app:
    container_name: github-app
    build: .
    image: github-app
    command: bash -c "rm -f tmp/pids/server.pid && tail -f /dev/null"
    volumes:
      - bundle_cache:/bundle
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
  db:
    image: postgres:10
    container_name: github-db
    restart: always
    volumes:
      -  db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
  redis:
    image: redis:4-stretch
    container_name: github-redis
    ports:
      - "6379:6379"

volumes:
  bundle_cache:
  db:
