development:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>

test:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: github-app_production
